import test from 'node:test';
import assert from 'node:assert/strict';
import {assignmentReplyText,selectAssignmentDecision,clearAssignmentDecision,replySubmissionAllowed,replyFormMarkup,mountAssignmentReplyForm} from '../packages/shared-ui/assignment-reply-form.js';
const original={decision:'',note:'',notesOpen:false,exactText:null};
test('decision alone is one explicit reply, not an immediate send',()=>{assert.equal(assignmentReplyText(selectAssignmentDecision(original,'good')),'Looks good');assert.equal(assignmentReplyText(selectAssignmentDecision(original,'changes')),'Needs changes');});
test('Needs changes opens notes, Looks good starts with optional notes hidden',()=>{assert.equal(selectAssignmentDecision(original,'changes').notesOpen,true);assert.equal(selectAssignmentDecision(original,'good').notesOpen,false);});
test('switching decisions preserves written notes and never duplicates decision text',()=>{const state=selectAssignmentDecision({...original,note:'Keep this exact note'},'changes');assert.equal(assignmentReplyText(selectAssignmentDecision(state,'good')),'Looks good\n\nKeep this exact note');assert.equal(selectAssignmentDecision(state,'good').notesOpen,true);});
test('Remove selection preserves notes and never changes a sent receipt',()=>{const state={...selectAssignmentDecision({...original,note:'Keep note'},'changes'),receipt:{report_id:'saved'}};const next=clearAssignmentDecision(state);assert.equal(next.decision,'');assert.equal(next.note,'Keep note');assert.equal(next.receipt,state.receipt);assert.equal(next.notesOpen,true);});
test('submission requires bound routing, content, byte-preserved intent and capacity',()=>{assert.equal(replySubmissionAllowed(original,{available:true}),false);assert.equal(replySubmissionAllowed({...original,note:'hello'},null),false);assert.equal(replySubmissionAllowed({...original,note:'hello'},{available:true}),true);assert.equal(replySubmissionAllowed({...original,note:'hello'},{available:true},true),false);assert.equal(replySubmissionAllowed({...original,note:'a'.repeat(8193)},{available:true}),false);});
test('an interrupted legacy reply retains its exact spaces and line breaks',()=>{assert.equal(assignmentReplyText({...original,decision:'good',note:'changed',exactText:'  Original\n\n ' }),'  Original\n\n ');});
test('markup uses one submit, conditional notes and a quiet remove-selection affordance',()=>{const html=replyFormMarkup();assert.equal((html.match(/type="submit"/g)||[]).length,1);assert.match(html,/data-clear-decision hidden>Remove selection/);assert.match(html,/data-note-region hidden/);assert.doesNotMatch(html,/Clear decision|reply to this work/);assert.match(html,/Nothing is sent until you choose Send reply/);});
class Element {
 constructor(value=''){this.value=value;this.disabled=false;this.checked=false;this.hidden=false;this.listeners={};this.attrs={};this.textContent='';this.children={};}
 addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);}
 setAttribute(name,value){this.attrs[name]=value;}
 querySelector(name){return this.children[name]??=(new Element());}
 focus(){this.focused=true;}
 async emit(type){for(const fn of this.listeners[type]||[])await fn({preventDefault(){},target:this});}
}
async function setup({previous=[],bindingOverride,sendDelay}={}){
 const keys=['form','textarea','[data-reply-status]','[data-send]','[data-note-region]','[data-toggle-note]','[data-clear-decision]','[data-recheck]','[data-refresh-status]','[data-reply-receipt]','[data-reply-diagnostic]','[data-reply-done]'];
 const elements=Object.fromEntries(keys.map(key=>[key,new Element()])),good=new Element('good'),changes=new Element('changes'),root={innerHTML:'',querySelector:key=>elements[key],querySelectorAll:()=>[good,changes]};
 const memory=new Map(previous),storage={getItem:key=>memory.get(key)||null,setItem:(key,value)=>memory.set(key,value)},calls=[],key='ctrl.assignment.reply.v2.ctrl.work';let done=0;
 const args={project:'ctrl',assignment:'work',expected_owner:'owner',expected_branch:'branch',artifact:{commit_sha:'a'.repeat(40)}};
 const api=async(url)=>{calls.push(['read',url]);return {available:true,args,...bindingOverride};};
 const send=async(input)=>{calls.push(['send',input.text]);if(sendDelay)await sendDelay;const receipt={report_id:'report',status:{queued:true}};storage.setItem(key,JSON.stringify({args:{...args,original_text:input.text,operation_id:'op'},receipt}));return {receipt,label:'saved in Relay · acknowledgement pending'};};
 const destroy=mountAssignmentReplyForm(root,{project:'ctrl',assignment:'work',claim:{owner:'owner',branch:'branch'},progress:{identities:{head_sha:'a'.repeat(40)}},api,storage,send,refresh:async()=>{calls.push(['refresh']);return {label:'reply acknowledged · native delivery unverified'};},onDone:()=>done++});
 await Promise.resolve();await Promise.resolve();return {elements,good,changes,memory,calls,key,destroy,getDone:()=>done};
}
test('selecting a decision does not send; one explicit submit saves one combined reply',async()=>{const h=await setup();await h.changes.emit('change');assert.equal(h.elements['[data-note-region]'].hidden,false);assert.equal(h.calls.filter(c=>c[0]==='send').length,0);h.elements.textarea.value='Fix the spacing';await h.elements.textarea.emit('input');await h.elements.form.emit('submit');assert.deepEqual(h.calls.filter(c=>c[0]==='send'),[['send','Needs changes\n\nFix the spacing']]);assert.equal(h.elements['[data-send]'].disabled,true);await h.elements.form.emit('submit');assert.equal(h.calls.filter(c=>c[0]==='send').length,1);h.destroy();});
test('clear decision keeps note and prior receipt',async()=>{const h=await setup();await h.good.emit('change');h.elements.textarea.value='keep';await h.elements.textarea.emit('input');await h.elements.form.emit('submit');const before=h.memory.get(h.key);await h.elements['[data-clear-decision]'].emit('click');assert.equal(h.elements.textarea.value,'keep');assert.equal(h.good.checked,false);assert.equal(h.memory.get(h.key),before);h.destroy();});
test('Done retains draft and exits without posting',async()=>{const h=await setup();h.elements.textarea.value='Draft survives';await h.elements.textarea.emit('input');await h.elements['[data-reply-done]'].emit('click');assert.equal(h.memory.get(h.key+'.draft'),'Draft survives');assert.equal(h.getDone(),1);assert.equal(h.calls.filter(c=>c[0]==='send').length,0);h.destroy();});
test('saved reply is retained after remount and is not automatically resent',async()=>{const text='Looks good';const h=await setup({previous:[['ctrl.assignment.reply.v2.ctrl.work.decision','good'],['ctrl.assignment.reply.v2.ctrl.work',JSON.stringify({args:{original_text:text},receipt:{report_id:'report',status:{queued:true}}})]]});assert.equal(h.elements['[data-send]'].disabled,true);assert.equal(h.elements['[data-refresh-status]'].hidden,false);await h.elements['[data-refresh-status]'].emit('click');assert.match(h.elements['[data-reply-status]'].textContent,/native delivery unverified/);assert.equal(h.calls.filter(c=>c[0]==='send').length,0);h.destroy();});
test('unconfirmed reply is restored verbatim for deliberate retry',async()=>{const text='  Pending exact\n reply  ';const h=await setup({previous:[['ctrl.assignment.reply.v2.ctrl.work',JSON.stringify({args:{original_text:text}})]]});assert.equal(h.elements.textarea.value,text);assert.equal(h.elements['[data-note-region]'].hidden,false);await h.elements.form.emit('submit');assert.deepEqual(h.calls.filter(c=>c[0]==='send'),[['send',text]]);h.destroy();});
test('mismatched recipient binding cannot enable or submit a reply',async()=>{const h=await setup({bindingOverride:{args:{project:'other',assignment:'work',expected_owner:'owner',expected_branch:'branch',artifact:{commit_sha:'a'.repeat(40)}}}});await h.good.emit('change');assert.equal(h.elements['[data-send]'].disabled,true);await h.elements.form.emit('submit');assert.equal(h.calls.filter(c=>c[0]==='send').length,0);h.destroy();});
test('rapid repeated submit while saving produces one operation',async()=>{let resolve;const waiting=new Promise(r=>resolve=r),h=await setup({sendDelay:waiting});await h.good.emit('change');const first=h.elements.form.emit('submit');await h.elements.form.emit('submit');assert.equal(h.calls.filter(c=>c[0]==='send').length,1);resolve();await first;h.destroy();});
