import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {fixture} from './fixture.mjs';
const app=await fixture(),browser=await chromium.launch({headless:true});const captures=[],errors=[];let activePage;await fs.mkdir('qa-evidence',{recursive:true});
try{for(const width of [1440,390,320]){const page=await browser.newPage({viewport:{width,height:900},colorScheme:'dark',reducedMotion:width===320?'reduce':'no-preference'});activePage=page;page.on('pageerror',e=>errors.push({width,message:e.message}));let sockets=[];await page.routeWebSocket('**/api/events*',ws=>{sockets.push(ws);ws.onClose(()=>{sockets=sockets.filter(s=>s!==ws);});ws.onMessage(data=>{if(data==='ping')ws.send('pong');});ws.send(JSON.stringify({type:'resync',cursor:'0'}));});
await page.goto(app.origin+'/#/today?project=field');await page.getByRole('heading',{name:'now',exact:true}).waitFor();await page.waitForURL('**/#/now?project=field');await page.locator('.work-viewer[data-summary-state=ready]').waitFor();assert.equal(await page.locator('.operator-nav [data-feature]').count(),5);await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.fonts.check('24px "Momo Trust Display"')),true);
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no horizontal overflow');await page.screenshot({path:`qa-evidence/now-${width}.png`});captures.push(`now-${width}.png`);
const trigger=page.locator('.operator-nav [data-relay-open]');await trigger.click();const dialog=page.getByRole('dialog',{name:'relay',exact:true});await dialog.waitFor();await dialog.locator('[data-relay-version]').filter({hasText:'2.0.fixture'}).waitFor();await page.waitForFunction(()=>{const r=document.querySelector('dialog').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;});
await page.locator('dialog[data-motion=settled]').waitFor();await page.screenshot({path:`qa-evidence/relay-panel-${width}.png`});captures.push(`relay-panel-${width}.png`);await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});await trigger.evaluate(el=>{if(document.activeElement!==el)throw Error('focus did not return');});assert.ok(page.url().includes('/now?project=field'));
await trigger.click();await dialog.waitFor();await page.goBack();await dialog.waitFor({state:'hidden'});assert.ok(page.url().includes('/now?project=field'));
await trigger.click();await dialog.waitFor();await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.querySelector('dialog').contains(document.activeElement)));await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});
// Event invalidation must refresh source immediately, well before the fallback minute.
app.progress.field[0].next_action='Instant update '+width;for(const socket of sockets)socket.send(JSON.stringify({type:'change',id:'1',topics:['project:field']}));await page.getByText('Instant update '+width,{exact:true}).first().waitFor({timeout:10000});
await page.locator('.operator-nav a[data-feature=inspector]').click();await page.getByRole('heading',{name:'inspector',exact:true}).waitFor();await page.locator('.work-viewer').waitFor();assert.ok(app.requests.includes('/api/visual?project=field'),'project filter must reach the evidence API before its60-item limit');await page.locator('.operator-nav [data-relay-open]').click();await page.getByRole('dialog',{name:'relay',exact:true}).waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});assert.ok(page.url().includes('/inspector#review'));
await page.screenshot({path:`qa-evidence/inspector-${width}.png`});captures.push(`inspector-${width}.png`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
if(width===1440){await page.locator('.presentation-menu summary').first().click();await page.locator('.presentation-customize summary').click();await page.selectOption('[name=desktop]','bottom');await page.locator('.presentation-menu summary').first().click();await page.locator('.operator-nav [data-relay-open]').click();await page.getByRole('dialog').waitFor();await page.locator('dialog[data-motion=settled]').waitFor();await page.screenshot({path:'qa-evidence/relay-desktop-bottom.png'});captures.push('relay-desktop-bottom.png');await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});}
if(width===390){await page.emulateMedia({colorScheme:'light'});await page.locator('.operator-nav [data-relay-open]').click();await page.locator('dialog[data-motion=settled]').waitFor();await page.screenshot({path:'qa-evidence/relay-panel-light-390.png'});captures.push('relay-panel-light-390.png');await page.setViewportSize({width:844,height:390});await page.waitForFunction(()=>{const r=document.querySelector('dialog').getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;});await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});}
await page.close();}
assert.deepEqual(errors,[]);await fs.writeFile('qa-evidence/result.json',JSON.stringify({ok:true,source_sha:process.env.CTRL_SOURCE_SHA||process.env.GITHUB_SHA,captures,checks:['Now alias and project context','five-item cohesive navigation','dialog Escape/Back/focus','mobile bounds','stream invalidation','Inspector navigation','desktop bottom layout','Momo embedded font','no page errors']},null,2));console.log('CTRL_BROWSER_PASS',JSON.stringify(captures));}catch(error){if(activePage&&!activePage.isClosed()){await activePage.screenshot({path:'qa-evidence/failure.png'}).catch(()=>{});await fs.writeFile('qa-evidence/failure.json',JSON.stringify({error:String(error),errors,body:await activePage.locator('body').innerText().catch(()=>''),url:activePage.url()},null,2));}throw error;}finally{await browser.close();await app.close();}
