import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';
export async function fixture(){const now=new Date().toISOString(),requests=[];const projects=[{id:'relay',name:'relay'},{id:'field',name:'field'}];const progress={relay:[{assignment:'relay-build',goal:'Connect ctrl with Relay',state:'working',stage:'implementation',next_action:'Verify the new control center',last_meaningful_progress_at:now,events:[]}],field:[{assignment:'field-check',goal:'Review the portrait workspace',state:'waiting-for-human',stage:'review',next_action:'Open the latest Inspector capture',last_meaningful_progress_at:now,events:[]}]};
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');requests.push(url.pathname);const json=(d,status=200)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(d));};
if(url.pathname==='/api/projects')return json({projects});if(url.pathname==='/api/workers')return json([]);if(url.pathname==='/api/relay-info')return json({version:'2.0.fixture'});
if(url.pathname==='/api/work-review'){let text='';for await(const chunk of req)text+=chunk;const input=JSON.parse(text);return json({ok:true,results:(input.items||[]).map(item=>({ok:true,key:[item.project,item.kind,item.id].map(encodeURIComponent).join('/'),record:null,etag:null}))});}
const project=url.pathname.match(/^\/api\/projects\/(relay|field)$/);if(project)return json({project:projects.find(p=>p.id===project[1]),coordination:{claims:progress[project[1]].map(p=>({id:p.assignment,state:'active'})),queue:[]}});
if(url.pathname.endsWith('/icon'))return json({status:'unavailable'});
const work=url.pathname.match(/^\/api\/progress\/(relay|field)$/);if(work)return json({project:work[1],progress:progress[work[1]],queue:[]});
if(url.pathname==='/api/visual')return json({evidence:[]});
if(url.pathname.startsWith('/api/'))return json({error:'fixture route unavailable'},404);
let name=url.pathname==='/'?'/index.html':url.pathname==='/inspector'?'/inspector.html':url.pathname;const target=path.resolve('dist','.'+name);if(!target.startsWith(path.resolve('dist')+path.sep))return json({},404);
try{const bytes=await fs.readFile(target);const type={'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png','.svg':'image/svg+xml','.json':'application/json'}[path.extname(target)]||'application/octet-stream';res.writeHead(200,{'Content-Type':type});res.end(bytes);}catch{json({},404);}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));return{origin:'http://127.0.0.1:'+server.address().port,progress,requests,close:()=>new Promise(r=>server.close(r))};}
