import test from 'node:test';import assert from 'node:assert/strict';
import worker,{permitted,forwarded} from '../worker/index.js';
import {validateEvent} from '../packages/shared-ui/relay-stream.js';
import {springStep} from '../packages/shared-ui/field-springs.js';
test('proxy denies unknown routes, unsafe methods, and encoded path tricks',()=>{assert.equal(permitted('/api/projects','GET'),true);assert.equal(permitted('/api/work-review','POST'),true);for(const path of ['/mcp','/api/source','/api/projects/../workers','/api/projects/a%2Fb','/api/workers/foo/token'])assert.equal(permitted(path,'POST'),false);assert.equal(permitted('/api/projects','DELETE'),false);});
test('deployment disabled and missing identity both fail closed',async()=>{const req=new Request('https://ctrl.loew.fi/');assert.equal((await worker.fetch(req,{})).status,503);assert.equal((await worker.fetch(req,{CTRL_ENABLED:'true',RELAY:{},ASSETS:{}})).status,401);});
test('changing requests retain actual origin and reject cross-origin before forwarding',async()=>{let calls=0;const env={CTRL_ENABLED:'true',ASSETS:{},RELAY:{fetch:async req=>{calls++;assert.equal(req.headers.get('Origin'),'https://ctrl.loew.fi');assert.equal(new URL(req.url).host,'ctrl.loew.fi');assert.equal(req.headers.get('Authorization'),null);assert.equal(req.headers.get('Cookie'),null);return Response.json({ok:true});}}};const make=origin=>new Request('https://ctrl.loew.fi/api/work-review',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','Cf-Access-Jwt-Assertion':'test-assertion',Authorization:'test-not-forwarded',Cookie:'test-not-forwarded'},body:'{}'});assert.equal((await worker.fetch(make('https://evil.example'),env)).status,403);assert.equal(calls,0);assert.equal((await worker.fetch(make('https://ctrl.loew.fi'),env)).status,200);assert.equal(calls,1);});
test('Relay authorization failures remain failures',async()=>{const res=await worker.fetch(new Request('https://ctrl.loew.fi/api/projects',{headers:{'Cf-Access-Jwt-Assertion':'invalid'}}),{CTRL_ENABLED:'true',ASSETS:{},RELAY:{fetch:async()=>new Response('denied',{status:403})}});assert.equal(res.status,403);});
test('events require bounded monotonic identities and small topics',()=>{assert.ok(validateEvent({type:'change',id:'12',topics:['projects']}));for(const value of [{type:'change',id:'-1',topics:[]},{type:'change',id:'1',topics:[{}]},{type:'change',id:'1',topics:['a'.repeat(81)]}])assert.equal(Boolean(validateEvent(value)),false);});
test('Field analytic spring preserves velocity and converges without frame coupling',()=>{let a={value:0,velocity:0};for(let i=0;i<180;i++)a=springStep(a.value,a.velocity,1,1/60);assert.ok(Math.abs(a.value-1)<.001);const x=springStep(.5,2,1,.01),y=springStep(x.value,x.velocity,1,.01),z=springStep(.5,2,1,.02);assert.ok(Math.abs(y.value-z.value)<1e-10);});

test('legacy Today path preserves project context under Now',async()=>{const r=await worker.fetch(new Request('https://ctrl.loew.fi/today?project=field',{headers:{'Cf-Access-Jwt-Assertion':'test'}}),{CTRL_ENABLED:'true',ASSETS:{},RELAY:{}});assert.equal(r.status,308);assert.equal(r.headers.get('Location'),'https://ctrl.loew.fi/#/now?project=field');});
