import {featureIconMarkup,canonicalFeature} from '../../../../packages/shared-ui/feature-icons.js';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {glyph} from '../../../../packages/shared-ui/glyphs.js';
export type MetricTile={title:string;value:string|number;note:string;icon:string;detail:ReactNode};
export function MetricTiles({tiles,label,className=''}:{tiles:MetricTile[];label:string;className?:string}){
 const [selected,setSelected]=useState<number|null>(null),dialog=useRef<HTMLDialogElement>(null),prior=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(selected!=null)dialog.current?.showModal();else{dialog.current?.close();prior.current?.focus();}},[selected]);
 const open=(index:number,origin?:HTMLElement)=>{prior.current=origin||document.activeElement as HTMLElement;setSelected(index);};
 return <><section className={'domain-telemetry control-mosaic '+className} aria-label={label}>{tiles.map((tile,index)=><article className="mosaic-panel domain-tile" key={tile.title} role="button" tabIndex={0} aria-label={'open '+tile.title+' details'} onClick={event=>{if(!(event.target as HTMLElement).closest('button,a,summary,[data-work-project]'))open(index,event.currentTarget);}} onKeyDown={event=>{if(event.target===event.currentTarget&&(event.key==='Enter'||event.key===' ')){event.preventDefault();open(index);}}}><header className="mosaic-heading"><span className="mosaic-glyph" aria-hidden="true" dangerouslySetInnerHTML={{__html:canonicalFeature(tile.icon)?featureIconMarkup(tile.icon):glyph(tile.icon)}}/><h2>{tile.title}</h2></header><strong className="mosaic-count">{tile.value}</strong><p>{tile.note}</p><div className="domain-full-detail">{tile.detail}</div><span className="mosaic-expand-hint">view details ›</span></article>)}</section><dialog className="work-detail-dialog telemetry-dialog" ref={dialog} aria-labelledby="domain-detail-heading" onCancel={event=>{event.preventDefault();setSelected(null);}}><header><h2 id="domain-detail-heading">{selected!=null?tiles[selected].title:label}</h2><button type="button" aria-label="close telemetry details" onClick={()=>setSelected(null)}>×</button></header><div className="work-detail-body"><button type="button" className="work-detail-back" onClick={()=>setSelected(null)}>‹ back to overview</button>{selected!=null&&<><p>{tiles[selected].value} · {tiles[selected].note}</p>{tiles[selected].detail}</>}</div></dialog></>;
}
