import {featureIconMarkup,canonicalFeature} from '../../../../packages/shared-ui/feature-icons.js';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {glyph} from '../../../../packages/shared-ui/glyphs.js';
export type MetricTile={title:string;value:string|number;note:string;icon:string;detail:ReactNode;visual?:ReactNode};
export function MetricTiles({tiles,label,className=''}:{tiles:MetricTile[];label:string;className?:string}){
 const [selected,setSelected]=useState<number|null>(null),dialog=useRef<HTMLDialogElement>(null),prior=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(selected!=null)dialog.current?.showModal();else{dialog.current?.close();prior.current?.focus();}},[selected]);
 const open=(index:number,origin?:HTMLElement)=>{prior.current=origin||document.activeElement as HTMLElement;setSelected(index);};
 return <><section className={'domain-telemetry control-mosaic '+className} aria-label={label}>{tiles.map((tile,index)=><article className="mosaic-panel domain-tile" key={tile.title} role="button" tabIndex={0} aria-label={'open '+tile.title+' details'} onClick={event=>{if(!(event.target as HTMLElement).closest('button,a,summary,[data-work-project]'))open(index,event.currentTarget);}} onKeyDown={event=>{if(event.target===event.currentTarget&&(event.key==='Enter'||event.key===' ')){event.preventDefault();open(index);}}}><header className="mosaic-heading"><span className="mosaic-glyph" aria-hidden="true" dangerouslySetInnerHTML={{__html:canonicalFeature(tile.icon)?featureIconMarkup(tile.icon):glyph(tile.icon)}}/><h2>{tile.title}</h2></header><div className="domain-metric-body"><div className="domain-metric-copy"><strong className="mosaic-count">{tile.value}</strong><p>{tile.note}</p></div>{tile.visual}</div><div className="domain-full-detail">{tile.detail}</div><span className="mosaic-expand-hint">view details ›</span></article>)}</section><dialog className="work-detail-dialog telemetry-dialog" ref={dialog} aria-labelledby="domain-detail-heading" onCancel={event=>{event.preventDefault();setSelected(null);}}><header><h2 id="domain-detail-heading">{selected!=null?tiles[selected].title:label}</h2><button type="button" aria-label="close telemetry details" onClick={()=>setSelected(null)}>×</button></header><div className="work-detail-body"><button type="button" className="work-detail-back" onClick={()=>setSelected(null)}>‹ back to overview</button>{selected!=null&&<><div className="domain-detail-summary"><div><strong>{tiles[selected].value}</strong><p>{tiles[selected].note}</p></div>{tiles[selected].visual}</div>{tiles[selected].detail}</>}</div></dialog></>;
}

export function MetricRecordGraphic({matches,kind,partial}:{matches:boolean[];kind:'ring'|'marks';partial:boolean}){
 const count=matches.filter(Boolean).length,total=matches.length,circumference=2*Math.PI*38;
 return <figure className={'metric-record-graphic metric-record-graphic--'+kind} data-record-count={count} data-record-total={total}>
  {!total?<div className="metric-record-empty">{partial?'Waiting for records':'No recorded work yet'}</div>:<>
   {kind==='ring'?<svg viewBox="0 0 100 100" aria-hidden="true"><circle className="metric-ring-track" cx="50" cy="50" r="38"/>{count>0&&<circle className="metric-ring-value" cx="50" cy="50" r="38" strokeDasharray={`${circumference*count/total} ${circumference}`}/>}<text x="50" y="54" textAnchor="middle">{count}/{total}</text></svg>:<div className="metric-record-marks" aria-hidden="true">{matches.slice(0,24).map((match,index)=><span key={index} data-matched={match}/>)}</div>}
   <figcaption>{count} of {total} loaded records{kind==='marks'&&total>24?' · first 24 shown':''}{partial?' · partial':''}</figcaption>
  </>}
 </figure>;
}

export type TelemetryRecord={id:string;title:string;project:string;state:string;note?:string;onOpen:()=>void};
export function TelemetryRecords({records,empty='No matching records are loaded.'}:{records:TelemetryRecord[];empty?:string}){
 const [search,setSearch]=useState(''),[project,setProject]=useState(''),[state,setState]=useState('');
 const projects=[...new Set(records.map(row=>row.project))],states=[...new Set(records.map(row=>row.state))];
 const visible=records.filter(row=>(!project||row.project===project)&&(!state||row.state===state)&&[row.title,row.project,row.note||''].join(' ').toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 return <><div className="work-view-controls work-detail-controls"><label className="work-search-compact"><span className="sr-only">search recorded data</span><input type="search" value={search} placeholder="find a record" onChange={event=>setSearch(event.target.value)}/></label><details className="work-control-menu"><summary><span aria-hidden="true" dangerouslySetInnerHTML={{__html:glyph('filter')}}/>filter records<span aria-hidden="true" dangerouslySetInnerHTML={{__html:glyph('next')}}/></summary><div className="work-control-panel"><p className="work-control-label">recorded state</p><div className="work-filter-bar" role="group" aria-label="recorded state">{['',...states].map(value=><button key={value} type="button" aria-pressed={state===value} onClick={()=>setState(value)}>{value||'everything'}</button>)}</div>{projects.length>1&&<label className="work-control-extension">project<select value={project} onChange={event=>setProject(event.target.value)}><option value="">all projects</option>{projects.map(value=><option key={value}>{value}</option>)}</select></label>}<footer className="work-controls-footer"><p>Filters change this loaded list.</p><button type="button" className="work-controls-done" onClick={event=>{event.currentTarget.closest('details')!.open=false;}}>done</button></footer></div></details></div><p className="work-detail-results" role="status">{visible.length} of {records.length} loaded records</p><ul className="work-detail-checklist">{visible.map(row=><li key={row.id}><button type="button" onClick={row.onOpen}><span aria-hidden="true" dangerouslySetInnerHTML={{__html:glyph('branch')}}/><span><strong>{row.title}</strong><small>{row.project} · {row.state}</small>{row.note&&<span className="work-detail-row-next">{row.note}</span>}</span><span aria-hidden="true" dangerouslySetInnerHTML={{__html:glyph('next')}}/></button></li>)}{!visible.length&&<li className="work-detail-empty">{records.length?'No records match. Try another filter or clear your search.':empty}</li>}</ul></>;
}
