import {useMemo} from 'react';
import {controlTelemetry} from '../../../../packages/shared-ui/control-telemetry.js';
import {ProgressRing} from './Telemetry';
import {ProjectBadge} from './ProjectBadge';
import type {DashboardSnapshot} from '../types';
export function TelemetryMosaic({snapshot}:{snapshot:DashboardSnapshot|null}){
 const model=useMemo(()=>controlTelemetry(snapshot,snapshot?Date.parse(snapshot.fetchedAt):Date.now()),[snapshot]);
 const max=Math.max(1,...model.activity.bins.map((b:any)=>b.count));
 const points=model.activity.bins.map((b:any,i:number)=>`${30+i*100},${150-b.count/max*110}`).join(' ');
 return <section className="control-mosaic" aria-label="recorded work overview">
  <article className="mosaic-panel mosaic-progress"><h2>recorded progress</h2><p>completed assignments in Relay's current record</p><div className="mosaic-progress-body"><ProgressRing percent={model.percent} label={model.pending?'record still loading':model.total?`${model.completed} of ${model.total} assignments complete`:'no assignments on record'}/><dl><div><dt>working</dt><dd>{model.pending?`${model.moving} observed`:model.moving}</dd></div><div><dt>waiting for a next step</dt><dd>{model.pending?`${model.waiting} observed`:model.waiting}</dd></div></dl></div></article>
  <article className="mosaic-panel"><h2>in motion</h2><strong className="mosaic-count">{model.activeProjects.length}{model.pending?' observed':''}</strong><p>products with current assignments</p><div className="mosaic-projects">{model.activeProjects.map((id:string)=><ProjectBadge key={id} project={id}/>)}</div><dl className="mosaic-overview"><div><dt>newest registered product</dt><dd>{model.newest?<ProjectBadge project={model.newest}/>:model.pending?'checking':'registration date not reported'}</dd></div><div><dt>most recorded updates</dt><dd>{model.mostUpdates?<><ProjectBadge project={model.mostUpdates.project}/><span>{model.mostUpdates.count} observed events</span></>:model.pending?'checking':'no event history reported'}</dd></div></dl></article>
  <article className="mosaic-panel mosaic-activity"><div className="mosaic-heading"><div><h2>activity</h2><p>{model.activity.count} timestamped events observed in the past six hours</p></div><strong className="mosaic-count">{model.activity.count}</strong></div>{model.activity.count?<svg viewBox="0 0 560 190" role="img" aria-label="Observed events per hour over the past six hours">{[0,1,2].map(i=><g key={i}><line x1="30" x2="530" y1={150-i*55} y2={150-i*55}/><text x="4" y={154-i*55}>{Math.round(max*i/2)}</text></g>)}<polyline points={points}/>{model.activity.bins.map((bin:any,i:number)=><g key={bin.at}><circle cx={30+i*100} cy={150-bin.count/max*110} r="4"><title>{new Date(bin.at).toLocaleTimeString()}: {bin.count} observed events</title></circle><text x={30+i*100} y="180" textAnchor="middle">{6-i}h ago</text></g>)}</svg>:<div className="mosaic-no-history">no timestamped activity available for this window</div>}<p className="mosaic-footnote">observed updates, not a complete activity ledger{model.pending?' · some projects are still loading or unavailable':''}{model.activity.undated?` · ${model.activity.undated} undated events excluded`:''}</p></article>
 </section>;
}
