import {brand} from '../../apps/web/public/brand.js';
import {glyph} from './glyphs.js';
import {springStep} from './field-springs.js';
import {fieldMotion} from './field-motion.js';
import {subscribeRelayStream} from './relay-stream.js';
export function relayTrigger(){return `<button type="button" class="relay-utility-trigger" data-relay-open data-feature="relay" aria-haspopup="dialog" aria-expanded="false" aria-controls="relay-engine-panel"><span class="glyph-chip"><img class="tool-mark" src="${brand.relay}" alt=""></span><span class="nav-copy"><strong>relay</strong><small>connection</small></span><span class="nav-chevron" aria-hidden="true">${glyph('next')}</span></button>`;}
export function relayTelemetry(){return `<button type="button" class="relay-telemetry" data-relay-open aria-haspopup="dialog" aria-expanded="false" aria-controls="relay-engine-panel"><img src="${brand.relay}" alt="" width="28" height="28"><span><strong>relay</strong><small data-relay-status>connecting</small></span><span class="relay-pulse" aria-hidden="true"><i></i><i></i><i></i></span></button>`;}
export function bindRelayUtility(){
 const dialog=document.createElement('dialog');dialog.id='relay-engine-panel';dialog.className='relay-engine-panel';dialog.setAttribute('aria-labelledby','relay-engine-title');
 dialog.innerHTML=`<div class="relay-sheet-handle" aria-hidden="true"></div><header class="relay-engine-heading"><img src="${brand.relay}" alt="" width="60" height="60"><div><h2 id="relay-engine-title">relay</h2><p>the connection behind ctrl</p></div><button type="button" data-relay-close aria-label="Close Relay">${glyph('close')}</button></header><div class="relay-engine-state"><span class="relay-pulse" aria-hidden="true"><i></i><i></i><i></i></span><strong data-relay-status>connecting</strong></div><dl><div><dt>MCP version</dt><dd data-relay-version>checking</dd></div><div><dt>Last contact</dt><dd data-relay-contact>not yet</dd></div><div><dt>Updates</dt><dd data-relay-delivery>connecting</dd></div></dl><p class="relay-engine-explainer">Relay connects project work, evidence and notifications. ctrl keeps it all in view.</p><p class="relay-engine-error" role="status" hidden></p><footer><button type="button" data-relay-refresh>Check connection</button><a href="https://relay.loew.fi" target="_blank" rel="noreferrer">Open Relay</a></footer>`;
 document.body.append(dialog);let source=null,open=false,frame=0,progress=1,velocity=0,target=1,last=0,historyKey=null,historyPending=false,disposed=false,lastContact=0,streamStatus='connecting',refreshing=false,restoreOverflow='';
 const signal=new AbortController(),motion=matchMedia('(prefers-reduced-motion: reduce)');
 const visibility=()=>{document.documentElement.dataset.ctrlHidden=String(document.hidden);};visibility();document.addEventListener('visibilitychange',visibility,{signal:signal.signal});
 function paint(){const anchor=source?.getBoundingClientRect();const rect=dialog.getBoundingClientRect();if(!anchor)return;const mobile=innerWidth<=600;const dx=mobile?0:anchor.left+anchor.width/2-(parseFloat(dialog.style.left)+dialog.offsetWidth/2);const dy=mobile?dialog.offsetHeight*.8:anchor.top+anchor.height/2-(parseFloat(dialog.style.top)+dialog.offsetHeight/2);dialog.style.transform=`translate3d(${dx*(1-progress)}px,${dy*(1-progress)}px,0) scale(${.88+.12*progress})`;dialog.style.opacity=String(Math.min(1,Math.max(0,progress*1.7)));dialog.style.setProperty('--relay-backdrop-opacity',String(Math.max(0,Math.min(1,progress))));}
 function position(){if(!dialog.open)return;const r=source?.getBoundingClientRect();if(innerWidth<=600){dialog.style.left='12px';dialog.style.top='auto';dialog.style.bottom='max(12px, env(safe-area-inset-bottom))';}else{dialog.style.bottom='auto';const width=Math.min(390,innerWidth-32);let left=r?r.right+14:(innerWidth-width)/2;let top=r?r.top:80;if(r&&r.top>innerHeight*.6){left=r.left+r.width/2-width/2;top=r.top-dialog.offsetHeight-18;}dialog.style.left=Math.max(16,Math.min(left,innerWidth-width-16))+'px';dialog.style.top=Math.max(16,Math.min(top,innerHeight-dialog.offsetHeight-16))+'px';}paint();}
 function finishClose(){if(open)return;dialog.close();dialog.style.transform='';document.body.style.overflow=restoreOverflow;source?.isConnected&&source.focus({preventScroll:true});}
 function tick(now){const dt=last?Math.min(.064,(now-last)/1000):1/60;last=now;const n=springStep(progress,velocity,target,dt,fieldMotion.spatial);progress=n.value;velocity=n.velocity;paint();if(Math.abs(progress-target)<.001&&Math.abs(velocity)<.005){frame=0;last=0;progress=target;dialog.dataset.motion='settled';paint();if(!open)finishClose();}else frame=requestAnimationFrame(tick);}
 function animate(next){target=next;dialog.dataset.motion='moving';if(motion.matches||document.documentElement.dataset.presentationMotion==='calm'){cancelAnimationFrame(frame);frame=0;progress=target;velocity=0;dialog.dataset.motion='settled';paint();if(!open)finishClose();return;}if(!frame){last=0;frame=requestAnimationFrame(tick);}}
 function state(){const text=streamStatus==='connected'?'connected':streamStatus==='paused'?'paused':streamStatus==='offline'?'offline':lastContact?'reconnecting':'connecting';document.querySelectorAll('[data-relay-status]').forEach(n=>n.textContent=text);document.querySelectorAll('.relay-pulse').forEach(n=>n.dataset.state=text);dialog.querySelector('[data-relay-delivery]').textContent=streamStatus==='connected'?'instant event stream':streamStatus==='paused'?'paused while hidden':'periodic fallback';dialog.querySelector('[data-relay-contact]').textContent=lastContact?new Date(lastContact).toLocaleTimeString([], {hour:'numeric',minute:'2-digit',second:'2-digit'}):'not yet';}
 async function refresh(){if(refreshing)return;refreshing=true;const button=dialog.querySelector('[data-relay-refresh]');button.disabled=true;const error=dialog.querySelector('.relay-engine-error');try{const r=await fetch('/api/relay-info',{signal:AbortSignal.any([signal.signal,AbortSignal.timeout(10000)]),headers:{Accept:'application/json'}});if(!r.ok)throw new Error('The engine could not be reached. Your loaded work stays available.');const d=await r.json();if(disposed)return;dialog.querySelector('[data-relay-version]').textContent=typeof d.version==='string'?d.version:'not reported';lastContact=Date.now();error.hidden=true;}catch(e){if(!disposed&&!signal.signal.aborted){error.textContent=e.message;error.hidden=false;dialog.querySelector('[data-relay-version]').textContent='unavailable';}}finally{refreshing=false;button.disabled=false;state();}}
 function expanded(value){document.querySelectorAll('[data-relay-open]').forEach(n=>n.setAttribute('aria-expanded',String(value)));}
 function show(trigger){if(historyPending)return;source=trigger;if(open)return;open=true;expanded(true);historyKey='relay-'+crypto.randomUUID();history.pushState({...history.state,ctrlRelay:historyKey},'',location.href);restoreOverflow=document.body.style.overflow;document.body.style.overflow='hidden';if(!dialog.open){progress=0;velocity=0;dialog.showModal();}position();animate(1);dialog.querySelector('[data-relay-close]').focus({preventScroll:true});void refresh();}
 function dismiss(pop=true){if(!open)return;open=false;expanded(false);animate(0);if(pop&&history.state?.ctrlRelay===historyKey){historyPending=true;history.back();}historyKey=null;}
 const click=e=>{const trigger=e.target.closest?.('[data-relay-open]');if(trigger){e.preventDefault();show(trigger);}if(e.target.closest?.('[data-relay-close]'))dismiss();if(e.target.closest?.('[data-relay-refresh]'))void refresh();};
 const outside=e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dismiss();};
 const cancel=e=>{e.preventDefault();dismiss();};const pop=()=>{historyPending=false;dismiss(false);};const hash=()=>dismiss(false);const resize=()=>{if(open)position();};
 document.addEventListener('click',click);dialog.addEventListener('click',outside);dialog.addEventListener('cancel',cancel);window.addEventListener('popstate',pop);window.addEventListener('hashchange',hash);window.addEventListener('resize',resize);motion.addEventListener('change',()=>animate(open?1:0),{signal:signal.signal});
 const unsubscribe=subscribeRelayStream(e=>{streamStatus=e.status;if(e.kind==='change'||e.kind==='resync'||e.kind==='heartbeat')lastContact=Date.now();state();});void refresh();
 return()=>{disposed=true;signal.abort();unsubscribe();cancelAnimationFrame(frame);document.removeEventListener('click',click);window.removeEventListener('popstate',pop);window.removeEventListener('hashchange',hash);window.removeEventListener('resize',resize);if(dialog.open){dialog.close();document.body.style.overflow=restoreOverflow;}if(history.state?.ctrlRelay===historyKey){const s={...history.state};delete s.ctrlRelay;history.replaceState(s,'',location.href);}dialog.remove();expanded(false);};
}
