import {openWorkCollection} from './work-details.js';
import {controlTelemetry} from './control-telemetry.js';
import {subscribeRelayDashboard} from './relay-dashboard.js';
import {brand} from '../../apps/web/public/brand.js';
import {glyph} from './glyphs.js';
import {springStep} from './field-springs.js';
import {fieldMotion} from './field-motion.js';
import {subscribeRelayStream} from './relay-stream.js';
export function relayTrigger(){return `<button type="button" class="relay-utility-trigger" data-relay-open data-feature="relay" aria-haspopup="dialog" aria-expanded="false" aria-controls="relay-engine-panel"><span class="glyph-chip"><img class="tool-mark" src="${brand.relay}" alt=""></span><span class="nav-copy"><strong>relay</strong><small>connection</small></span><span class="nav-chevron" aria-hidden="true">${glyph('next')}</span></button>`;}
export function relayTelemetry(){return `<button type="button" class="relay-telemetry" data-relay-open aria-haspopup="dialog" aria-expanded="false" aria-controls="relay-engine-panel"><img src="${brand.relay}" alt="" width="28" height="28"><span><strong>relay</strong><small data-relay-status>connecting</small></span><span class="relay-pulse" aria-hidden="true"><i></i><i></i><i></i></span></button>`;}
export function bindRelayUtility(){
 const dialog=document.createElement('dialog');dialog.id='relay-engine-panel';dialog.className='relay-engine-panel';dialog.setAttribute('aria-labelledby','relay-engine-title');
 dialog.innerHTML=`<div class="relay-sheet-handle" aria-hidden="true"></div><header class="relay-engine-heading"><img src="${brand.relay}" alt="" width="60" height="60"><div><h2 id="relay-engine-title">relay</h2><p>the connection behind ctrl</p></div><div class="relay-engine-actions"><a class="relay-refresh-tools" href="https://chatgpt.com/settings/plugins-settings/plugin_asdk_app_6abe234861d881919e30db65d656492f" target="_blank" rel="noreferrer" title="Open ChatGPT to refresh Relay tools">${glyph('refresh')}<span class="sr-only">refresh tools in ChatGPT</span></a><button type="button" data-relay-refresh aria-label="check connection" title="check connection">${glyph('refresh')}</button><a href="https://relay.loew.fi" target="_blank" rel="noreferrer">Open Relay</a></div><button type="button" data-relay-close aria-label="Close Relay">${glyph('close')}</button></header><div class="relay-engine-state"><span class="relay-pulse" aria-hidden="true"><i></i><i></i><i></i></span><strong data-relay-status>connecting</strong></div><section class="relay-compact-mosaic" aria-label="recorded workspace telemetry" data-relay-mosaic><p>workspace record loading</p></section><dl><div><dt>MCP version</dt><dd data-relay-version>checking</dd></div><div><dt>Last contact</dt><dd data-relay-contact>not yet</dd></div><div><dt>Updates</dt><dd data-relay-delivery>connecting</dd></div></dl><p class="relay-engine-explainer">Relay connects project work, evidence and notifications. ctrl keeps it all in view.</p><p class="relay-check-result" data-relay-check-result role="status" aria-live="polite">Ready to check</p><p class="relay-engine-error" role="status" hidden></p>`;
 document.body.append(dialog);let source=null,open=false,frame=0,progress=1,velocity=0,target=1,last=0,historyKey=null,historyPending=false,disposed=false,lastContact=0,streamStatus='connecting',refreshing=false,restoreOverflow='',latestSnapshot=null;
 const signal=new AbortController(),motion=matchMedia('(prefers-reduced-motion: reduce)');
 const visibility=()=>{document.documentElement.dataset.ctrlHidden=String(document.hidden);};visibility();document.addEventListener('visibilitychange',visibility,{signal:signal.signal});
 function paint(){const anchor=source?.getBoundingClientRect();const rect=dialog.getBoundingClientRect();if(!anchor)return;const mobile=innerWidth<=600;const dx=mobile?0:anchor.left+anchor.width/2-(parseFloat(dialog.style.left)+dialog.offsetWidth/2);const dy=mobile?dialog.offsetHeight*.8:anchor.top+anchor.height/2-(parseFloat(dialog.style.top)+dialog.offsetHeight/2);dialog.style.transform=`translate3d(${dx*(1-progress)}px,${dy*(1-progress)}px,0) scale(${.88+.12*progress})`;dialog.style.opacity=String(Math.min(1,Math.max(0,progress*1.7)));dialog.style.setProperty('--relay-backdrop-opacity',String(Math.max(0,Math.min(1,progress))));}
 function position(){if(!dialog.open)return;const r=source?.getBoundingClientRect();if(innerWidth<=600){dialog.style.left='0';dialog.style.top='0';dialog.style.bottom='0';}else{dialog.style.bottom='auto';const width=Math.min(640,innerWidth-32);let left=(innerWidth-width)/2;let top=(innerHeight-dialog.offsetHeight)/2;dialog.style.left=Math.max(16,Math.min(left,innerWidth-width-16))+'px';dialog.style.top=Math.max(16,Math.min(top,innerHeight-dialog.offsetHeight-16))+'px';}paint();}
 function finishClose(){if(open)return;dialog.close();dialog.style.transform='';document.body.style.overflow=restoreOverflow;source?.isConnected&&source.focus({preventScroll:true});}
 function tick(now){const dt=last?Math.min(.064,(now-last)/1000):1/60;last=now;const n=springStep(progress,velocity,target,dt,fieldMotion.spatial);progress=n.value;velocity=n.velocity;paint();if(Math.abs(progress-target)<.001&&Math.abs(velocity)<.005){frame=0;last=0;progress=target;dialog.dataset.motion='settled';paint();if(!open)finishClose();}else frame=requestAnimationFrame(tick);}
 function animate(next){target=next;dialog.dataset.motion='moving';if(motion.matches||document.documentElement.dataset.presentationMotion==='calm'){cancelAnimationFrame(frame);frame=0;progress=target;velocity=0;dialog.dataset.motion='settled';paint();if(!open)finishClose();return;}if(!frame){last=0;frame=requestAnimationFrame(tick);}}
 function state(){const text=refreshing?'checking':streamStatus==='connected'?'connected':streamStatus==='paused'?'paused':streamStatus==='offline'?'offline':lastContact?'reconnecting':'connecting';document.querySelectorAll('[data-relay-status]').forEach(n=>n.textContent=text);document.querySelectorAll('.relay-pulse').forEach(n=>n.dataset.state=text);dialog.querySelector('[data-relay-delivery]').textContent=streamStatus==='connected'?'instant event stream':streamStatus==='paused'?'paused while hidden':'periodic fallback';dialog.querySelector('[data-relay-contact]').textContent=lastContact?new Date(lastContact).toLocaleTimeString([], {hour:'numeric',minute:'2-digit',second:'2-digit'}):'not yet';}
 async function refresh(){
  if(refreshing||disposed)return;
  refreshing=true;dialog.dataset.checking='true';
  const button=dialog.querySelector('[data-relay-refresh]'),result=dialog.querySelector('[data-relay-check-result]'),error=dialog.querySelector('.relay-engine-error');
  button.disabled=true;button.setAttribute('aria-busy','true');result.textContent='Checking connection…';result.dataset.result='checking';error.hidden=true;state();
  const started=performance.now();let outcome='error';
  try{
   const r=await fetch('/api/relay-info',{signal:AbortSignal.any([signal.signal,AbortSignal.timeout(10000)]),headers:{Accept:'application/json'}});
   if(!r.ok)throw new Error('Could not reach Relay. Your loaded work is still available.');
   const d=await r.json();if(disposed)return;
   dialog.querySelector('[data-relay-version]').textContent=typeof d.version==='string'?d.version:'not reported';lastContact=Date.now();outcome='success';
  }catch(e){if(!disposed&&!signal.signal.aborted){error.textContent=e.name==='TimeoutError'?'Relay took too long to respond. Try again.':e.message;error.hidden=false;}}
  finally{
   await new Promise(resolve=>setTimeout(resolve,Math.max(0,600-(performance.now()-started))));
   refreshing=false;if(disposed)return;
   dialog.dataset.checking='false';button.disabled=false;button.removeAttribute('aria-busy');
   result.dataset.result=outcome;result.textContent=(outcome==='success'?'Connection verified':'Connection check failed')+' · '+new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit',second:'2-digit'});state();
  }
 }
 function expanded(value){document.querySelectorAll('[data-relay-open]').forEach(n=>n.setAttribute('aria-expanded',String(value)));}
 function show(trigger){if(historyPending)return;source=trigger;if(open)return;open=true;expanded(true);historyKey='relay-'+crypto.randomUUID();history.pushState({...history.state,ctrlRelay:historyKey},'',location.href);restoreOverflow=document.body.style.overflow;document.body.style.overflow='hidden';if(!dialog.open){progress=0;velocity=0;dialog.showModal();}position();animate(1);dialog.querySelector('[data-relay-close]').focus({preventScroll:true});void refresh();}
 function dismiss(pop=true){if(!open)return;open=false;expanded(false);animate(0);if(pop&&history.state?.ctrlRelay===historyKey){historyPending=true;history.back();}historyKey=null;}
 const click=e=>{const trigger=e.target.closest?.('[data-relay-open]');if(trigger){e.preventDefault();show(trigger);}if(e.target.closest?.('[data-relay-close]'))dismiss();if(e.target.closest?.('[data-relay-refresh]'))void refresh();};
 const outside=e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dismiss();};
 const trapFocus=e=>{if(e.key!=='Tab'||!dialog.open)return;const nodes=[...dialog.querySelectorAll('a[href],button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),summary,[tabindex="0"]')].filter(node=>node.getClientRects().length&&!node.closest('[hidden]'));if(!nodes.length){e.preventDefault();dialog.focus();return;}const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};
 dialog.addEventListener('keydown',trapFocus,{signal:signal.signal});
 const cancel=e=>{e.preventDefault();dismiss();};const pop=()=>{historyPending=false;dismiss(false);};const hash=()=>dismiss(false);const resize=()=>{if(open)position();};
 document.addEventListener('click',click);dialog.addEventListener('click',outside);dialog.addEventListener('cancel',cancel);window.addEventListener('popstate',pop);window.addEventListener('hashchange',hash);window.addEventListener('resize',resize);motion.addEventListener('change',()=>animate(open?1:0),{signal:signal.signal});
 const stopDashboard=subscribeRelayDashboard(snapshot=>{
  latestSnapshot=snapshot;
  const host=dialog.querySelector('[data-relay-mosaic]'),m=controlTelemetry(snapshot,snapshot?Date.parse(snapshot.fetchedAt):Date.now());
  const percent=m.percent,arc=percent===undefined?0:percent*2.51327,max=Math.max(1,...m.activity.bins.map(b=>b.count));
  const chart=m.activity.count?`<svg class="relay-compact-chart" viewBox="0 0 300 64" role="img" aria-label="${m.activity.count} observed events in six hourly bins"><polyline points="${m.activity.bins.map((b,i)=>`${10+i*56},${54-b.count/max*44}`).join(' ')}"/></svg>`:'<p class="relay-compact-no-history">no timestamped activity in this window</p>';
  host.innerHTML=`<article class="relay-compact-progress" role="button" tabindex="0" data-relay-drill="progress" aria-label="explore recorded progress"><h3>recorded progress</h3><div class="relay-compact-ring"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="40"/>${percent>0?`<circle class="relay-compact-arc" cx="50" cy="50" r="40" stroke-dasharray="${arc} 251.327"/>`:''}</svg><strong>${percent===undefined?'—':percent+'%'}</strong></div><p>${!snapshot?'workspace record loading':m.pending?'partial record · checking':m.total?`${m.completed} of ${m.total} assignments complete`:'no assignments reported'}</p></article><article class="relay-compact-counts" role="button" tabindex="0" data-relay-drill="motion" aria-label="explore current assignments"><h3>in motion</h3><strong>${m.activeProjects.length}${m.pending?' observed':''}</strong><p>products with current work</p><dl><div><dt>working</dt><dd>${m.moving}${m.pending?' observed':''}</dd></div><div><dt>needs your input</dt><dd>${m.needs.length}${m.pending?' observed':''}</dd></div></dl></article><article class="relay-compact-activity" role="button" tabindex="0" data-relay-drill="activity" aria-label="explore activity assignments"><h3>activity <span>${m.activity.count}</span></h3>${chart}<p>observed events · past six hours${m.pending?' · partial record':''}${m.activity.undated?' · undated events excluded':''}</p></article>`;
  if(open)position();
 });
 const drill=target=>{const m=controlTelemetry(latestSnapshot,latestSnapshot?Date.parse(latestSnapshot.fetchedAt):Date.now()),kind=target.dataset.relayDrill;let rows=m.current,title='current assignments';if(kind==='progress'){rows=Object.entries(latestSnapshot?.coordination||{}).flatMap(([project,record])=>(record.claims||[]).map(item=>({project,item:{...item,assignment:item.id}})));title='recorded project work';}else if(kind==='activity'){const keys=new Set(m.activity.events.map(row=>row.project+':'+row.assignment));rows=m.work.rows.filter(row=>keys.has(row.project+':'+row.item.assignment));title='assignments with recent updates';}openWorkCollection({title,rows});};
 dialog.addEventListener('click',event=>{const target=event.target.closest('[data-relay-drill]');if(target)drill(target);},{signal:signal.signal});
 dialog.addEventListener('keydown',event=>{if(event.target.matches('[data-relay-drill]')&&['Enter',' '].includes(event.key)){event.preventDefault();drill(event.target);}},{signal:signal.signal});
 const unsubscribe=subscribeRelayStream(e=>{streamStatus=e.status;if(e.kind==='change'||e.kind==='resync'||e.kind==='heartbeat')lastContact=Date.now();state();});void refresh();
 return()=>{disposed=true;signal.abort();unsubscribe();stopDashboard();cancelAnimationFrame(frame);document.removeEventListener('click',click);window.removeEventListener('popstate',pop);window.removeEventListener('hashchange',hash);window.removeEventListener('resize',resize);if(dialog.open){dialog.close();document.body.style.overflow=restoreOverflow;}if(history.state?.ctrlRelay===historyKey){const s={...history.state};delete s.ctrlRelay;history.replaceState(s,'',location.href);}dialog.remove();expanded(false);};
}

